version: "3"
services:
  mysql-db:
    image: mysql:latest
    restart: always
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops_project_db
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
  spring-boot-app:
  # Add the necessary configuration for your Spring Boot application here
    depends_on:
      - mysql-db
    image: samarbouzezi/devops_project:spring
    ports:
      - "8082:8082"
