# version: "3"
# services:
#   mysql-db:
#     image: mysql:latest
#     restart: always
#     container_name: mysql-db
#     ports:
#       - "3306:3306"
#     environment:
#       - MYSQL_ROOT_PASSWORD=
#       - MYSQL_DATABASE=devops_project_db
#     volumes:
#       - ./data.sql:/docker-entrypoint-initdb.d/data.sql
#   spring-boot-app:
#   # Add the necessary configuration for your Spring Boot application here
#     depends_on:
#       - mysql-db
#     image: samarbouzezi/devops_project:spring
#     ports:
#       - "8082:8082"

  # angular-app:
  #   image: ikbel436/frontachat
  #   container_name: docker-compose-angular-app
  #   ports:
  #     - "4200:80"
  #   depends_on:
  #     - spring-boot-app
  #   networks:
  #     - my-network
  
version: '3'
services:
  mysql-db:
    image: mysql:latest
    container_name: devops-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=devops_project_db
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - my-network
  spring-boot-app:
    image: samarbouzezi/devops_project:spring
    container_name: devops_project_spring
    ports:
      - "8082:8082"
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://devops-db:3306/devops_project_db?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    networks:
      - my-network
networks:
  my-network:
