version: "3"

services:
  mysql-db:
    image: mysql:latest
    container_name: devops-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=mydatabase
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - my-network
    restart: on-failure

  spring-boot-app:
    image: samarbouzezi/devops_project:spring
    container_name: devops_project_spring

    ports:
      - "8088:8082"
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/mydatabase?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    networks:
      - my-network
    restart: on-failure

  angular-app:
    image: samarbouzezi/devops_project:angular
    container_name: devops_project_angular

    ports:
      - "4208:80"
    depends_on:
      - spring-boot-app
    networks:
      - my-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: always
    networks:
      - my-network
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    restart: always
    networks:
      - my-network

networks:
  my-network:
  
# version: '3'
# services:
#   mysql-db:
#     image: mysql:latest
#     container_name: devops-db
#     ports:
#       - "3306:3306"
#     restart: always
#     environment:
#       - MYSQL_ALLOW_EMPTY_PASSWORD=yes
#       - MYSQL_DATABASE=devops_project_db
#     volumes:
#       - ./data.sql:/docker-entrypoint-initdb.d/data.sql
#     networks:
#       - my-network
#   spring-boot-app:
#     image: samarbouzezi/devops_project:spring
#     container_name: devops_project_spring
#     ports:
#       - "8082:8082"
#     restart: always
#     depends_on:
#       - mysql-db
#     environment:
#       - SPRING_DATASOURCE_URL=jdbc:mysql://devops-db:3306/devops_project_db?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#       - SPRING_DATASOURCE_USERNAME=root
#       - SPRING_DATASOURCE_PASSWORD=
#     networks:
#       - my-network
# networks:
#   my-network:
