version: "3"
services:
  mysql-db:
    image: mysql:latest
    container_name: docker-compose-mysql-db-1
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
  spring-boot-app:
    image: 1kbe1436/achat
    ports:
      - "8089:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-compose-mysql-db-1:3306/achatdb?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliant
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
